name             'nmap-cookbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures nmap-cookbook'
long_description 'Installs/Configures nmap-cookbook'
version          '0.1.0'
