name             'nmap'
maintainer       'Merouane Atig'
maintainer_email 'merouane.atig@gmail.com'
license          'All rights reserved'
description      'Installs Nmap with capabilities'
long_description 'Installs Nmap and add the ability to run Nmap as an unprivileged user on Linux systems by using capabilities'
version          '0.2.0'
